"""Bootstrap tests run before any harness or regression validation."""
import os
from pathlib import Path
import subprocess
import sys

import pyarrow.feather as feather
import pytest
import validation_firewall as guard


@pytest.mark.parametrize("relative", [
    "raw/male-cns/v1.0/connectome-weights-male-cns-v1.0-minconf-0.5.feather",
    "raw/male-cns/v1.0/body-annotations-male-cns-v1.0-minconf-0.5.feather",
    "raw/male-cns/v1.0/body-neurotransmitters-male-cns-v1.0.feather",
    "raw/neuron-metadata.json", "provenance/male-cns-v1.0.json",
    "provenance/task007-mapping-summary.json", "unknown-registered-source.bin",
])
def test_blocked_before_content(relative):
    assert guard.ACTIVE
    path = guard.ROOT / "data" / relative
    with pytest.raises(guard.SourceAccessDenied):
        path.read_bytes()
    with pytest.raises(guard.SourceAccessDenied):
        feather.read_table(path)


def test_generated_and_temp_and_source_allowed(tmp_path):
    import pyarrow as pa
    path = tmp_path / "generated.feather"
    feather.write_feather(pa.table({"value": [1]}), path)
    assert feather.read_table(path).to_pydict() == {"value": [1]}
    text = tmp_path / "synthetic.txt"
    text.write_text("synthetic")
    assert text.read_text() == "synthetic"
    assert "def install" in Path(guard.__file__).read_text()


def test_subprocess_guard():
    code = "import validation_firewall as g; assert g.ACTIVE; g.check(g.ROOT/'data/provenance/male-cns-v1.0.json')"
    result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
    assert result.returncode != 0
    assert "SourceAccessDenied" in result.stderr


def test_child_cannot_drop_guard(tmp_path):
    """Permit the mandatory entrypoint; reject activation before workload."""
    marker = tmp_path / "workload-executed"
    command = [sys.executable, guard.CHILD_ENTRY, "-c",
               f"from pathlib import Path; Path({str(marker)!r}).write_text('executed')"]
    assert guard.mandatory_child(command)
    result = subprocess.run(command, env={}, capture_output=True, text=True)
    parent_launch_rejected = False
    child_started = result.returncode == 78
    child_rejected_startup = "FIREWALL_REQUIRED_BUT_NOT_ACTIVE" in result.stderr
    workload_executed = marker.exists()
    assert parent_launch_rejected is False
    assert child_started is True
    assert child_rejected_startup is True
    assert workload_executed is False


def test_native_reader_denies_synthetic_sentinel(tmp_path, monkeypatch):
    """Exercise native coverage using generated bytes, never a real payload."""
    import pyarrow as pa
    import pyarrow._feather as native
    path = tmp_path / "generated-native-coverage.feather"
    feather.write_feather(pa.table({"synthetic_sentinel": [19]}), path)
    monkeypatch.setattr(guard, "DENIED_ROOTS", [*guard.DENIED_ROOTS, tmp_path])
    with pytest.raises(guard.SourceAccessDenied):
        native.FeatherReader(str(path), use_memory_map=False)
